
import { Language, SplitMode, ModelType, SubtitleStyle } from './types';

export const SUPPORTED_LANGUAGES = [
  { value: 'English', label: 'English', flag: '🇺🇸', code: 'en' },
  { value: 'Vietnamese', label: 'Tiếng Việt', flag: '🇻🇳', code: 'vi' },
  { value: 'Japanese', label: '日本語', flag: '🇯🇵', code: 'ja' },
  { value: 'Korean', label: '한국어', flag: '🇰🇷', code: 'ko' },
  { value: 'Chinese (Simplified)', label: '简体中文', flag: '🇨🇳', code: 'zh-CN' },
  { value: 'Chinese (Traditional)', label: '繁體中文', flag: '🇹🇼', code: 'zh-TW' },
  { value: 'Spanish', label: 'Español', flag: '🇪🇸', code: 'es' },
  { value: 'French', label: 'Français', flag: '🇫🇷', code: 'fr' },
  { value: 'German', label: 'Deutsch', flag: '🇩🇪', code: 'de' },
  { value: 'Italian', label: 'Italiano', flag: '🇮🇹', code: 'it' },
  { value: 'Portuguese', label: 'Português', flag: '🇵🇹', code: 'pt' },
  { value: 'Russian', label: 'Русский', flag: '🇷🇺', code: 'ru' },
  { value: 'Hindi', label: 'हिन्दी', flag: '🇮🇳', code: 'hi' },
  { value: 'Thai', label: 'ไทย', flag: '🇹🇭', code: 'th' },
  { value: 'Indonesian', label: 'Bahasa Indonesia', flag: '🇮🇩', code: 'id' },
  { value: 'Arabic', label: 'العربية', flag: '🇸🇦', code: 'ar' },
  { value: 'Turkish', label: 'Türkçe', flag: '🇹🇷', code: 'tr' },
  { value: 'Dutch', label: 'Nederlands', flag: '🇳🇱', code: 'nl' },
  { value: 'Polish', label: 'Polski', flag: '🇵🇱', code: 'pl' },
  { value: 'Swedish', label: 'Svenska', flag: '🇸🇪', code: 'sv' },
  { value: 'Filipino', label: 'Filipino', flag: '🇵🇭', code: 'tl' },
  { value: 'Malay', label: 'Bahasa Melayu', flag: '🇲🇾', code: 'ms' },
  { value: 'Ukrainian', label: 'Українська', flag: '🇺🇦', code: 'uk' },
  { value: 'Greek', label: 'Ελληνικά', flag: '🇬🇷', code: 'el' },
  { value: 'Czech', label: 'Čeština', flag: '🇨🇿', code: 'cs' },
  { value: 'Danish', label: 'Dansk', flag: '🇩🇰', code: 'da' },
  { value: 'Finnish', label: 'Suomi', flag: '🇫🇮', code: 'fi' },
  { value: 'Hungarian', label: 'Magyar', flag: '🇭🇺', code: 'hu' },
  { value: 'Norwegian', label: 'Norsk', flag: '🇳🇴', code: 'no' },
  { value: 'Romanian', label: 'Română', flag: '🇷🇴', code: 'ro' },
  { value: 'Slovak', label: 'Slovenčina', flag: '🇸🇰', code: 'sk' },
  { value: 'Bengali', label: 'বাংলা', flag: '🇧🇩', code: 'bn' },
  { value: 'Urdu', label: 'اردو', flag: '🇵🇰', code: 'ur' },
  { value: 'Persian', label: 'فارسی', flag: '🇮🇷', code: 'fa' },
  { value: 'Hebrew', label: 'עברית', flag: '🇮🇱', code: 'he' }
];

export const FONT_FAMILIES = [
  { value: 'Inter, sans-serif', label: 'Inter' },
  { value: '"SF Pro Display", sans-serif', label: 'SF Pro' },
  { value: 'Arial, sans-serif', label: 'Arial' },
  { value: '"Times New Roman", serif', label: 'Times New Roman' },
  { value: '"Courier New", monospace', label: 'Courier New' },
  { value: 'Georgia, serif', label: 'Georgia' },
  { value: 'Impact, sans-serif', label: 'Impact' },
  { value: 'Verdana, sans-serif', label: 'Verdana' },
  { value: 'Tahoma, sans-serif', label: 'Tahoma' },
  { value: 'Montserrat, sans-serif', label: 'Montserrat' },
  { value: 'Oswald, sans-serif', label: 'Oswald' },
  { value: 'Raleway, sans-serif', label: 'Raleway' },
  { value: '"Playfair Display", serif', label: 'Playfair Display' },
  { value: '"Roboto Mono", monospace', label: 'Roboto Mono' },
  { value: 'Ubuntu, sans-serif', label: 'Ubuntu' },
  { value: '"Open Sans", sans-serif', label: 'Open Sans' },
  { value: 'Kanit, sans-serif', label: 'Kanit' },
  { value: 'Be Vietnam Pro, sans-serif', label: 'Be Vietnam Pro' },
  { value: '"Lexend Deca", sans-serif', label: 'Lexend Deca' },
  { value: 'Lobster, cursive', label: 'Lobster' },
  { value: '"Pacifico", cursive', label: 'Pacifico' },
];

export const DEFAULT_SUBTITLE_STYLE: SubtitleStyle = {
  fontSize: 24,
  fontFamily: 'Inter, sans-serif',
  textColor: '#ffffff',
  backgroundColor: '#000000',
  showBackground: true,
  backgroundOpacity: 0.6,
  borderRadius: 8,
  padding: 12,
  fontWeight: 'bold',
  fontStyle: 'normal',
  textDecoration: 'none',
  highlightWords: true,
  highlightColor: '#44d62c',
  highlightBold: true,
  highlightItalic: false,
  highlightUnderline: false,
  textAlign: 'center',
  verticalPosition: 85,
  horizontalPosition: 50,
  maxWidth: 90,
  showGlow: true,
  glowColor: '#44d62c',
  glowOpacity: 0.5,
  glowBlur: 15,
  showSecondarySubtitle: false,
};

export const LANGUAGE_CODE_MAP: Record<string, string> = SUPPORTED_LANGUAGES.reduce((acc, lang) => {
  acc[lang.value] = lang.code.toUpperCase();
  return acc;
}, {} as Record<string, string>);

export const MODEL_OPTIONS = [
  { value: ModelType.GEMINI, label: 'Gemini 3 Flash' },
];

export const DEFAULT_MAX_CHARS = 40;

const BASE_EN = {
  appTitle: 'SubGenius',
  tagline: 'AI Powered Subtitle Generator',
  description: 'Create professional subtitles in seconds using the power of Gemini 3.',
  config: 'CONFIG',
  modelSelect: 'Transcription Engine',
  apiKeyLabel: 'Gemini API Settings',
  selectKeyBtn: 'SELECT PERSONAL KEY',
  useDefaultKey: 'Use System Default Key',
  useDefaultKeyHelp: 'Standard speed. No billing required from your side.',
  usePersonalKey: 'Use Personal API Key',
  usePersonalKeyHelp: 'Recommended for long files to avoid truncation or quota limits.',
  saveClose: 'SAVE & CLOSE',
  targetLang: 'Target Languages',
  targetLangHelp: 'Note: Translations are generated using high-accuracy Cloud AI.',
  splitRules: 'Split Rules',
  splitModes: [
    { value: SplitMode.SENTENCE, label: 'Sentence', hint: 'Natural flow' },
    { value: SplitMode.SINGLE_WORD, label: 'Word', hint: '1 word per line' },
    { value: SplitMode.THREE_WORDS, label: 'Groups', hint: '3 words per line' },
    { value: SplitMode.SHORT_PHRASE, label: 'Phrase', hint: 'Max 6 words' },
  ],
  generateBtn: 'GENERATE',
  processing: 'PROCESSING...',
  cancel: 'CANCEL',
  uploadTitle: 'Upload Audio',
  uploadDesc: 'MP3, WAV, M4A, MP4',
  ready: 'PROJECT SETTINGS',
  readyDesc: 'Upload audio or record to begin sequence.',
  generatedTitle: 'GENERATED CUES',
  exportSRT: 'Export as SRT',
  exportASS: 'Export as ASS (Styled)',
  exportDOC: 'Word Document (.doc)',
  exportExcel: 'Excel (CSV)',
  exportJSON: 'Project File (JSON)',
  exportJSONDesc: 'Single file backup including audio',
  importSRT: 'Import SRT',
  importCSV: 'Import CSV',
  importSRTHelp: 'Upload an .srt file to replace text in the current tab.',
  importCSVHelp: 'Upload a .csv file to completely replace the current project data.',
  saveProject: 'SAVE',
  savePrompt: 'Enter a name for your project:',
  projects: 'HISTORY',
  noProjects: 'No saved projects found.',
  replace: 'Replace',
  replaceAll: 'ALL',
  search: 'Search',
  recording: 'Recording...',
  stopRec: 'STOP RECORDING',
  recTitle: 'Record Voice',
  recDesc: 'Click to start',
  analyzing: 'Analyzing audio...',
  decoding: 'Decoding audio data...',
  resampling: 'Resampling to 16kHz...',
  transcribing: 'Executing transcription...',
  translating: 'Refining translations...',
  initSpeechModel: 'Initializing Speech AI...',
  initTranslatorModel: 'Initializing Translator AI...',
  original: 'ORIG',
  refreshTranslation: 'Translate',
  refreshHelp: 'Re-translate based on current Original text',
  reference: 'REFERENCE (ORIGINAL)',
  translation: 'TRANSLATION',
  printBtn: 'PRINT TO PDF',
  newProject: 'NEW',
  history: 'HISTORY',
  deleteConfirm: 'Delete this project? This cannot be undone.',
  renameTitle: 'Rename Project',
  toastSaved: 'Project Saved Successfully!',
  toastNew: 'New Project Started',
  toastExport: 'Project Exported',
  noSegmentsSearch: 'No segments matching search',
  clearSearch: 'Clear Search',
  liveEditor: 'Live Editor',
  standbySeek: 'Standby / Seeking Audio',
  focusedEditing: 'Focused Editing',
  focusedSearch: 'Focused Search',
  textUpdateTip: 'Text updates instantly on the main grid',
  exportTitle: 'Select Export Format',
  downloadFiles: 'Download Files',
  apiStatus: 'AI Engine Status',
  authError: 'Auth or Quota error. Please check your API Key or switch to a personal one.',
  generalError: 'Error occurred during AI processing.',
  importBtn: 'IMPORT FILE',
  togglePlayer: 'Toggle Player',
  playerSize: 'Player Size',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  keyRequired: 'Please select a personal API Key or use the system default.',
  searchPlaceholder: 'Search segments...',
  viewModeGrid: 'Grid View',
  viewModeText: 'Text Review',
  processingChunk: 'Processing chunk',
  noMedia: 'No media connected',
  selectMedia: 'Select Media File',
  selectMediaHelp: 'Please select a media file to start previewing and editing timeline',
  ok: 'OK',
  close: 'CLOSE',
  start: 'Start',
  end: 'End',
  rename: 'Rename',
  delete: 'Delete',
  speaker: 'Speaker',
  subtitleStyle: 'Subtitle Style',
  fontSize: 'Size',
  fontColor: 'Color',
  bgColor: 'Background',
  bgOpacity: 'Opacity',
  borderRadius: 'Rounded',
  padding: 'Padding',
  highlight: 'Highlight',
  highlightPerWord: 'Word Highlight',
  textAlign: 'Alignment',
  yPosition: 'Position (Y)',
  xPosition: 'Position (X)',
  maxWidth: 'Max Width',
  glow: 'Glow Effect',
  glowColor: 'Glow Color',
  glowOpacity: 'Glow Opacity',
  glowBlur: 'Glow Spread',
  exportVideo: 'Export Video',
  exportSubtitles: 'Export Subtitles',
  exportProject: 'Export Project',
  videoFormat: 'Video Format',
  renderingVideo: 'Rendering Video...',
  renderComplete: 'Video Rendered Successfully',
  guideTitle: 'User Guide',
  fontSearch: 'Search font...',
  uploadFont: 'Upload custom font',
  showSecondary: 'Show Original (Dual-Sub)',
  originalReference: 'Reference Original:',
  undo: 'Undo',
  splitTool: 'Split Tool',
  trimTool: 'Trim Tool',
  selectTool: 'Select Tool',
  timecodeJump: 'Jump to Timecode',
  themeSelect: 'Theme Selection',
  guide: {
    title: 'SubGenius AI - User Guide',
    tagline: 'Professional AI-Powered Subtitle Generation Suite',
    version: 'Official Documentation - Version 5.0',
    c1: { title: '01. Overview', desc: 'SubGenius AI utilizes Gemini 3 for ultra-fast audio transcription with millisecond word-alignment and high-quality translation.' },
    c2: { title: '02. Timeline Editor', subtitle: 'Advanced Editing Tools', desc: 'Use the Select Tool (V) for moving, Split Tool (C) for cutting segments, and Trim Tool (Shift) for simultaneous dual-edge trimming. Undo (Ctrl+Z) is available for quick corrections.' },
    c3: { title: '03. Pro Styling & Themes', uploadTitle: 'Style Palette', uploadDesc: 'Customize fonts, colors, and background. Use the Palette icon to change the overall app theme and gradients.', recTitle: 'Dual-Sub Mode', recDesc: 'Display original text alongside translations for bilingual viewers.' },
    c4: { title: '04. Search & Replace', subtitle: 'Mass Editing', desc: 'Use the Search panel to instantly find and replace terms across all segments and languages.' },
    c5: { title: '05. Exporting', subtitle: 'Pro Formats', desc: 'Export to SRT, ASS (Styled), or Video Overlay. Use Project JSON for a complete backup including the audio file.' },
    c6: { title: '06. Navigation', srtTitle: 'Timecode Jump', srtDesc: 'Click on the timecode in the timeline to jump to a specific position instantly.', csvTitle: 'Keyboard Shortcuts', csvDesc: 'C: Split, V: Select, Shift: Dual Trim, Ctrl+Z: Undo.' },
    c7: { title: '07. Privacy', desc: 'Data is processed securely. We never store your audio or subtitles on our own servers permanently.' }
  }
};

export const UI_TEXT: Record<string, typeof BASE_EN> = {
  en: BASE_EN,
  vn: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'Tạo Phụ Đề Bằng AI',
    description: 'Tạo phụ đề chuyên nghiệp trong giây lát sử dụng sức mạnh của Gemini 3.',
    config: 'CẤU HÌNH',
    importBtn: 'NHẬP FILE',
    togglePlayer: 'Ẩn/Hiện Video',
    playerSize: 'Kích thước Video',
    zoomIn: 'Phóng to',
    zoomOut: 'Thu nhỏ',
    apiKeyLabel: 'Cấu hình Gemini API',
    selectKeyBtn: 'CHỌN API KEY CÁ NHÂN',
    useDefaultKey: 'Sử dụng Key mặc định',
    useDefaultKeyHelp: 'Nhanh và miễn phí. Không yêu cầu thanh toán từ bạn.',
    usePersonalKey: 'Sử dụng Key cá nhân',
    usePersonalKeyHelp: 'Khuyên dùng cho file dài để tránh giới hạn hạn mức.',
    saveClose: 'LƯU & ĐÓNG',
    targetLang: 'Ngôn ngữ đích',
    targetLangHelp: 'Lưu ý: Bản dịch được tạo bằng AI Cloud độ chính xác cao.',
    splitRules: 'Quy tắc ngắt dòng',
    splitModes: [
      { value: SplitMode.SENTENCE, label: 'Theo câu', hint: 'Dòng chảy tự nhiên' },
      { value: SplitMode.SINGLE_WORD, label: 'Từng từ', hint: '1 từ mỗi dòng' },
      { value: SplitMode.THREE_WORDS, label: 'Nhóm từ', hint: '3 từ mỗi dòng' },
      { value: SplitMode.SHORT_PHRASE, label: 'Cụm từ', hint: 'Tối đa 6 từ' },
    ],
    generateBtn: 'TẠO',
    processing: 'ĐANG XỬ LÝ...',
    cancel: 'HỦY',
    uploadTitle: 'Tải File Audio',
    uploadDesc: 'MP3, WAV, M4A, MP4',
    ready: 'THIẾT LẬP DỰ ÁN',
    readyDesc: 'Tải lên âm thanh hoặc ghi âm để bắt đầu.',
    exportSRT: 'Xuất file SRT',
    exportASS: 'Xuất file ASS (Định dạng Pro)',
    exportDOC: 'Văn bản Word (.doc)',
    exportExcel: 'Excel (CSV)',
    exportJSON: 'Tệp Dự Án (JSON)',
    exportJSONDesc: 'Sao lưu duy nhất một tệp gồm cả âm thanh',
    importSRT: 'Nhập SRT',
    importCSV: 'Nhập CSV',
    saveProject: 'LƯU',
    savePrompt: 'Nhập tên cho dự án:',
    projects: 'LỊCH SỬ',
    history: 'LỊCH SỬ',
    noProjects: 'Chưa có dự án nào.',
    replace: 'Thay thế',
    replaceAll: 'TẤT CẢ',
    search: 'Tìm kiếm',
    recording: 'Đang ghi âm...',
    stopRec: 'DỪNG GHI ÂM',
    recTitle: 'Ghi âm',
    recDesc: 'Nhấn để bắt đầu',
    analyzing: 'Phân tích âm thanh...',
    decoding: 'Giải mã dữ liệu...',
    resampling: 'Đang chuyển đổi 16kHz...',
    transcribing: 'Trích xuất văn bản...',
    translating: 'Dịch thuật...',
    initSpeechModel: 'Khởi tạo AI giọng nói...',
    initTranslatorModel: 'Khởi tạo AI dịch thuật...',
    original: 'GỐC',
    refreshTranslation: 'Dịch',
    refreshHelp: 'Dịch lại dựa trên nội dung gốc',
    reference: 'THAM CHIẾU (GỐC)',
    translation: 'BẢN DỊCH',
    printBtn: 'XUẤT PDF',
    newProject: 'MỚI',
    deleteConfirm: 'Xóa dự án này? Thao tác này không thể hoàn tác.',
    renameTitle: 'Đổi tên dự án',
    rename: 'Đổi tên',
    delete: 'Xóa',
    speaker: 'Người nói',
    liveEditor: 'Trình chỉnh sửa',
    processingChunk: 'Đang xử lý đoạn',
    subtitleStyle: 'Kiểu Phụ Đề',
    fontSize: 'Kích cỡ',
    fontColor: 'Màu chữ',
    bgColor: 'Màu nền',
    bgOpacity: 'Độ mờ nền',
    borderRadius: 'Bo góc',
    padding: 'Căn lề',
    highlight: 'Làm nổi bật',
    highlightPerWord: 'Theo từng từ',
    textAlign: 'Căn lề chữ',
    yPosition: 'Vị trí (Y)',
    xPosition: 'Vị trí (X)',
    maxWidth: 'Dài tối đa',
    glow: 'Hiệu ứng đổ bóng',
    glowColor: 'Màu bóng',
    glowOpacity: 'Độ mờ bóng',
    glowBlur: 'Độ lan tỏa',
    exportVideo: 'Xuất Video',
    exportSubtitles: 'Xuất Phụ đề',
    exportProject: 'Xuất Dự án',
    videoFormat: 'Định dạng Video',
    renderingVideo: 'Đang xử lý Video...',
    renderComplete: 'Đã xuất Video thành công',
    toastSaved: 'Đã lưu thành công!',
    toastNew: 'Bắt đầu dự án mới',
    toastExport: 'Đã xuất dữ liệu',
    viewModeGrid: 'Dạng lưới',
    viewModeText: 'Dạng văn bản',
    noMedia: 'CHƯA KẾT NỐI MEDIA',
    selectMedia: 'CHỌN FILE MEDIA',
    selectMediaHelp: 'Vui lòng chọn tệp phương tiện để bắt đầu xem trước và chỉnh sửa timeline',
    searchPlaceholder: 'Tìm kiếm đoạn...',
    focusedEditing: 'Chỉnh sửa tập trung',
    focusedSearch: 'Tìm kiếm tập trung',
    ok: 'ĐỒNG Ý',
    close: 'ĐÓNG',
    start: 'Bắt đầu',
    end: 'Kết thúc',
    exportTitle: 'Chọn định dạng xuất',
    guideTitle: 'Hướng dẫn sử dụng',
    fontSearch: 'Tìm font...',
    uploadFont: 'Tải font của bạn',
    showSecondary: 'Hiện tiếng Gốc (Phụ đề kép)',
    originalReference: 'Tham chiếu tiếng gốc:',
    undo: 'Hoàn tác',
    splitTool: 'Công cụ Cắt',
    trimTool: 'Công cụ Trim',
    selectTool: 'Công cụ Chọn',
    timecodeJump: 'Nhảy tới Timecode',
    themeSelect: 'Tùy chọn Chủ đề',
    guide: {
      title: 'SubGenius AI - Hướng dẫn',
      tagline: 'Bộ công cụ tạo phụ đề chuyên nghiệp bằng AI',
      version: 'Tài liệu chính thức - Phiên bản 5.0',
      c1: { title: '01. Tổng quan', desc: 'SubGenius AI sử dụng Gemini 3 để chuyển đổi âm thanh siêu tốc, căn lề từng từ chính xác đến từng mili giây và dịch thuật chất lượng cao.' },
      c2: { title: '02. Trình chỉnh sửa Timeline', subtitle: 'Công cụ chỉnh sửa nâng cao', desc: 'Sử dụng Công cụ Chọn (V) để di chuyển, Công cụ Cắt (C) để chia đoạn, và Công cụ Trim (Shift) để thay đổi đồng thời điểm nối giữa 2 đoạn. Sử dụng Hoàn tác (Ctrl+Z) để quay lại.' },
      c3: { title: '03. Tùy chỉnh Pro & Chủ đề', uploadTitle: 'Bảng màu & Kiểu', uploadDesc: 'Tùy chỉnh font, màu sắc và nền. Sử dụng biểu tượng Palette để thay đổi chủ đề và gradient của ứng dụng.', recTitle: 'Phụ đề kép', recDesc: 'Hiển thị đồng thời văn bản gốc và bản dịch cho người xem song ngữ.' },
      c4: { title: '04. Tìm & Thay thế', subtitle: 'Chỉnh sửa hàng loạt', desc: 'Sử dụng bảng Tìm kiếm để tìm và thay thế nhanh các thuật ngữ trên tất cả các phân đoạn và ngôn ngữ.' },
      c5: { title: '05. Xuất bản', subtitle: 'Định dạng Pro', desc: 'Xuất ra SRT, ASS (Có định dạng) hoặc Video Overlay. Dùng Tệp Dự Án JSON để sao lưu toàn bộ dự án bao gồm cả âm thanh.' },
      c6: { title: '06. Điều hướng', srtTitle: 'Nhảy tới Timecode', srtDesc: 'Nhấp vào timecode trên timeline để nhảy tới vị trí chính xác ngay lập tức.', csvTitle: 'Phím tắt', csvDesc: 'C: Cắt, V: Chọn, Shift: Trim kép, Ctrl+Z: Hoàn tác.' },
      c7: { title: '07. Bảo mật', desc: 'Dữ liệu được xử lý an toàn. Chúng tôi không bao giờ lưu trữ vĩnh viễn âm thanh hay phụ đề của bạn trên máy chủ của mình.' }
    }
  },
  jp: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'AI字幕ジェネレーター',
    description: 'Gemini 3の力を利用して、プロフェッショナルな字幕を数秒で作成します。',
    config: '設定',
    apiKeyLabel: 'Gemini API設定',
    selectKeyBtn: '個人APIキーを選択',
    useDefaultKey: 'システムデフォルトキーを使用',
    useDefaultKeyHelp: '標準速度。請求は発生しません。',
    usePersonalKey: '個人APIキーを使用',
    usePersonalKeyHelp: '長いファイルやクォータ制限を回避するために推奨されます。',
    saveClose: '保存して閉じる',
    targetLang: 'ターゲット言語',
    targetLangHelp: '注：翻訳は高精度のクラウドAIを使用して生成されます。',
    splitRules: '分割ルール',
    splitModes: [
        { value: SplitMode.SENTENCE, label: '文', hint: '自然な流れ' },
        { value: SplitMode.SINGLE_WORD, label: '単語', hint: '1行に1単語' },
        { value: SplitMode.THREE_WORDS, label: 'グループ', hint: '1行に3単語' },
        { value: SplitMode.SHORT_PHRASE, label: 'フレーズ', hint: '最大6単語' },
    ],
    generateBtn: '生成する',
    processing: '処理中...',
    cancel: 'キャンセル',
    uploadTitle: '音声をアップロード',
    uploadDesc: 'MP3, WAV, M4A, MP4',
    ready: 'プロジェクト設定',
    readyDesc: '音声ファイルをアップロードするか、録音を開始してください。',
    exportSRT: 'SRTを書き出す',
    exportASS: 'ASSを書き出す (スタイル付き)',
    exportExcel: 'Excel (CSV)',
    exportJSON: 'プロジェクトファイル (JSON)',
    exportJSONDesc: '音声を含む単一ファイルのバックアップ',
    importSRT: 'SRTをインポート',
    importCSV: 'CSVをインポート',
    saveProject: '保存',
    savePrompt: 'プロジェクト名を入力してください：',
    projects: '履歴',
    history: '履歴',
    noProjects: '保存されたプロジェクトはありません。',
    replace: '置換',
    replaceAll: 'すべて置換',
    search: '検索',
    recording: '録音中...',
    stopRec: '録音停止',
    recTitle: '音声を録音',
    recDesc: 'クリックして開始',
    analyzing: '音声を分析中...',
    decoding: 'データをデコード中...',
    resampling: '16kHzにリサンプリング中...',
    transcribing: '文字起こしを実行中...',
    translating: '翻訳を調整中...',
    original: 'オリジナル',
    refreshTranslation: '翻訳',
    refreshHelp: '元のテキストに基づいて再翻訳',
    reference: '参照 (オリジナル)',
    translation: '翻訳',
    printBtn: 'PDFに印刷',
    newProject: '新規',
    deleteConfirm: 'このプロジェクトを削除しますか？この操作は取り消せません。',
    renameTitle: 'プロジェクト名の変更',
    rename: '名前変更',
    delete: '削除',
    speaker: '話者',
    subtitleStyle: '字幕スタイル',
    fontSize: 'サイズ',
    fontColor: '色',
    bgColor: '背景',
    bgOpacity: '不透明度',
    borderRadius: '角丸',
    padding: 'パディング',
    highlight: 'ハイライト',
    highlightPerWord: '単語ハイライト',
    textAlign: '配置',
    yPosition: '位置 (Y)',
    xPosition: '位置 (X)',
    maxWidth: '最大幅',
    exportVideo: 'ビデオを書き出す',
    exportSubtitles: '字幕を書き出す',
    exportProject: 'プロジェクトを書き出す',
    videoFormat: 'ビデオ形式',
    renderingVideo: 'ビデオをレンダリング中...',
    renderComplete: 'ビデオの書き出しが完了しました',
    toastSaved: 'プロジェクトが保存されました！',
    toastNew: '新しいプロジェクトを開始しました',
    toastExport: 'エクスポートされました',
    searchPlaceholder: 'セグメントを検索...',
    focusedEditing: 'フォーカス編集',
    focusedSearch: 'フォーカス検索',
    textUpdateTip: 'グリッド上でテキストが即座に更新されます',
    exportTitle: 'エクスポート形式を選択',
    downloadFiles: 'ファイルをダウンロード',
    apiStatus: 'AIエンジンの状態',
    ok: 'OK',
    close: '閉じる',
    start: '開始',
    end: '終了',
    noMedia: 'メディア未接続',
    selectMedia: 'メディアファイルを選択',
    selectMediaHelp: 'タイムラインのプレビューと編集を開始するには、メディアファイルを選択してください',
    guideTitle: 'ユーザーガイド',
    fontSearch: 'フォントを検索...',
    uploadFont: 'カスタムフォントをアップロード',
    showSecondary: '原文を表示 (デュアル字幕)',
    originalReference: '原文参照:',
    undo: '元に戻す',
    splitTool: '分割ツール',
    trimTool: 'トリムツール',
    selectTool: '選択ツール',
    timecodeJump: 'タイムコードへジャンプ',
    themeSelect: 'テーマ選択',
    guide: {
      title: 'SubGenius AI - ユーザーガイド',
      tagline: 'プロフェッショナルなAI字幕作成ツール',
      version: '公式ドキュメント - バージョン 5.0',
      c1: { title: '01. 概要', desc: 'SubGenius AIはGemini 3を使用して、ミリ秒単位の単語整列と高品質な翻訳で超高速な音声文字起こしを実現します。' },
      c2: { title: '02. タイムラインエディタ', subtitle: '高度な編集ツール', desc: '選択ツール(V)で移動、分割ツール(C)でセグメントのカット、トリムツール(Shift)で両端の同時トリミングが可能です。元に戻す(Ctrl+Z)で素早い修正ができます。' },
      c3: { title: '03. プロスタイルとテーマ', uploadTitle: 'スタイルパレット', uploadDesc: 'フォント、色、背景をカスタマイズ。パレットアイコンを使用して、アプリ全体のテーマとグラデーションを変更できます。', recTitle: 'デュアル字幕モード', recDesc: 'バイリンガルの視聴者のために、翻訳と並んで原文を表示します。' },
      c4: { title: '04. 検索と置換', subtitle: '一括編集', desc: '検索パネルを使用して、すべてのセグメントと言語にわたって用語を即座に検索して置換します。' },
      c5: { title: '05. エクスポート', subtitle: 'プロ形式', desc: 'SRT、ASS（スタイル付き）、またはビデオオーバーレイにエクスポート。音声ファイルを含む完全なバックアップにはプロジェクトJSONを使用します。' },
      c6: { title: '06. ナビゲーション', srtTitle: 'タイムコードジャンプ', srtDesc: 'タイムラインのタイムコードをクリックして、特定の位置に即座にジャンプします。', csvTitle: 'キーボードショートカット', csvDesc: 'C: 分割, V: 選択, Shift: デュアルトリム, Ctrl+Z: 元に戻す' },
      c7: { title: '07. プライバシー', desc: 'データは安全に処理されます。音声や字幕を弊社のサーバーに永久に保存することはありません。' }
    }
  },
  de: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'KI-gestützter Untertitel-Generator',
    config: 'KONFIG',
    targetLang: 'Zielsprachen',
    generateBtn: 'GENERIEREN',
    processing: 'VERARBEITUNG...',
    cancel: 'ABBRECHEN',
    uploadTitle: 'Audio hochladen',
    exportSRT: 'Als SRT exportieren',
    saveProject: 'SPEICHERN',
    projects: 'VERLAUF',
    search: 'Suche',
    recording: 'Aufnahme...',
    original: 'ORIG',
    translation: 'ÜBERSETZUNG',
    newProject: 'NEU',
    subtitleStyle: 'Untertitel-Stil',
    fontSize: 'Größe',
    fontColor: 'Farbe',
    bgColor: 'Hintergrund',
    bgOpacity: 'Deckkraft',
    textAlign: 'Ausrichtung',
    maxWidth: 'Max. Breite',
    exportVideo: 'Video exportieren',
    exportSubtitles: 'Untertitel exportieren',
    exportProject: 'Projekt exportieren',
    videoFormat: 'Videoformat',
    renderingVideo: 'Video wird gerendert...',
    ok: 'OK',
    close: 'SCHLIESSEN',
    start: 'Start',
    end: 'Ende',
    noMedia: 'Kein Medium verbunden',
    selectMedia: 'Mediendatei auswählen',
    selectMediaHelp: 'Bitte wählen Sie eine Mediendatei aus, um mit der Vorschau und Bearbeitung der Timeline zu beginnen',
    guideTitle: 'Benutzerhandbuch',
    showSecondary: 'Original anzeigen (Dual-Sub)',
    originalReference: 'Originalreferenz:',
    undo: 'Rückgängig',
    splitTool: 'Schneidewerkzeug',
    trimTool: 'Trim-Werkzeug',
    selectTool: 'Auswahlwerkzeug',
    timecodeJump: 'Zu Zeitcode springen',
    themeSelect: 'Themenauswahl',
    guide: {
      title: 'SubGenius AI - Benutzerhandbuch',
      tagline: 'Professionelle KI-Untertitel-Suite',
      version: 'Offizielle Dokumentation - V5.0',
      c1: { title: '01. Übersicht', desc: 'SubGenius AI nutzt Gemini 3 für ultraschnelle Audiotranskription mit präziser Wortausrichtung.' },
      c2: { title: '02. Timeline-Editor', subtitle: 'Erweiterte Werkzeuge', desc: 'Nutzen Sie das Auswahlwerkzeug (V), das Schneidewerkzeug (C) und das Trim-Werkzeug (Shift). Rückgängig (Ctrl+Z) ist für schnelle Korrekturen verfügbar.' },
      c3: { title: '03. Pro Styling & Themen', uploadTitle: 'Farbpalette', uploadDesc: 'Anpassung von Schriftarten und Farben. Nutzen Sie das Paletten-Icon für App-Themen.', recTitle: 'Dual-Modus', recDesc: 'Zweisprachige Anzeige.' },
      c4: { title: '04. Suche', subtitle: 'Massenbearbeitung', desc: 'Finden und Ersetzen über alle Segmente.' },
      c5: { title: '05. Export', subtitle: 'Formate', desc: 'SRT, ASS oder Video-Overlay.' },
      c6: { title: '06. Navigation', srtTitle: 'Zeitcode-Sprung', srtDesc: 'Klicken Sie auf den Zeitcode, um sofort zu springen.', csvTitle: 'Tastenkürzel', csvDesc: 'C: Schneiden, V: Auswählen, Shift: Trimmen, Ctrl+Z: Rückgängig.' },
      c7: { title: '07. Datenschutz', desc: 'Sichere Verarbeitung. Keine dauerhafte Speicherung.' }
    }
  },
  fr: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'Générateur de sous-titres IA',
    config: 'CONFIG',
    targetLang: 'Langues cibles',
    generateBtn: 'GÉNÉRER',
    processing: 'TRAITEMENT...',
    cancel: 'ANNULER',
    uploadTitle: 'Charger Audio',
    exportSRT: 'Exporter en SRT',
    saveProject: 'ENREGISTRER',
    projects: 'HISTORIQUE',
    search: 'Chercher',
    recording: 'Enregistrement...',
    original: 'ORIG',
    translation: 'TRADUCTION',
    newProject: 'NOUVEAU',
    subtitleStyle: 'Style des sous-titres',
    fontSize: 'Taille',
    fontColor: 'Couleur',
    bgColor: 'Arrière-plan',
    bgOpacity: 'Opacité',
    textAlign: 'Alignement',
    maxWidth: 'Largeur max',
    exportVideo: 'Exporter Vidéo',
    exportSubtitles: 'Exporter les sous-titres',
    exportProject: 'Exporter le projet',
    videoFormat: 'Format Vidéo',
    renderingVideo: 'Rendu Vidéo...',
    ok: 'OK',
    close: 'FERMER',
    start: 'Début',
    end: 'Fin',
    noMedia: 'Aucun média connecté',
    selectMedia: 'Sélectionner un fichier média',
    selectMediaHelp: 'Veuillez sélectionner un fichier média pour commencer à prévisualiser et à éditer la timeline',
    guideTitle: 'Guide utilisateur',
    showSecondary: 'Afficher l\'original (Dual-Sub)',
    originalReference: 'Référence originale :',
    undo: 'Annuler',
    splitTool: 'Outil de coupe',
    trimTool: 'Outil de rognage',
    selectTool: 'Outil de sélection',
    timecodeJump: 'Aller au code temporel',
    themeSelect: 'Sélection du thème',
    guide: {
      title: 'SubGenius AI - Guide Utilisateur',
      tagline: 'Suite professionnelle de génération de sous-titres',
      version: 'Documentation officielle - V5.0',
      c1: { title: '01. Aperçu', desc: 'Utilise Gemini 3 pour une transcription ultra-rapide.' },
      c2: { title: '02. Éditeur Timeline', subtitle: 'Outils avancés', desc: 'Utilisez l\'outil de sélection (V), l\'outil de coupe (C) et l\'outil de rognage (Shift). Annuler (Ctrl+Z) est disponible.' },
      c3: { title: '03. Style & Thèmes', uploadTitle: 'Palette', uploadDesc: 'Personnalisation des polices et thèmes via l\'icône Palette.', recTitle: 'Mode bilingue', recDesc: 'Affichage simultané.' },
      c4: { title: '04. Recherche', subtitle: 'Édition de masse', desc: 'Remplacer des termes globalement.' },
      c5: { title: '05. Exportation', subtitle: 'Formats Pro', desc: 'SRT, ASS ou incrustration vidéo.' },
      c6: { title: '06. Navigation', srtTitle: 'Saut temporel', srtDesc: 'Cliquez sur le code temporel để nhảy tới vị trí.', csvTitle: 'Raccourcis', csvDesc: 'C: Couper, V: Sélectionner, Shift: Rognage, Ctrl+Z: Annuler.' },
      c7: { title: '07. Confidentialité', desc: 'Traitement sécurisé. Pas de stockage permanent.' }
    }
  },
  cn: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'AI 智能字幕生成器',
    config: '配置',
    targetLang: '目标语言',
    generateBtn: '生成',
    processing: '正在处理...',
    cancel: '取消',
    uploadTitle: '上传音频',
    exportSRT: '导出为 SRT',
    saveProject: '保存',
    projects: '历史记录',
    search: '搜索',
    recording: '正在录音...',
    original: '原文',
    translation: '翻译',
    newProject: '新建',
    subtitleStyle: '字幕样式',
    fontSize: '大小',
    fontColor: '颜色',
    bgColor: '背景',
    bgOpacity: '不透明度',
    textAlign: '对齐',
    maxWidth: '最大宽度',
    exportVideo: '导出视频',
    exportSubtitles: '导出字幕',
    exportProject: '导出项目',
    videoFormat: '视频格式',
    renderingVideo: '正在渲染视频...',
    ok: '确定',
    close: '关闭',
    start: '开始',
    end: '结束',
    noMedia: '未连接媒体',
    selectMedia: '选择媒体文件',
    selectMediaHelp: '请选择媒体文件以开始预览 and 编辑时间轴',
    guideTitle: '用户指南',
    showSecondary: '显示原文 (双语字幕)',
    originalReference: '原文参考:',
    undo: '撤销',
    splitTool: '切割工具',
    trimTool: '修剪工具',
    selectTool: '选择工具',
    timecodeJump: '跳转至时间码',
    themeSelect: '主题选择',
    guide: {
      title: 'SubGenius AI - 用户指南',
      tagline: '专业级 AI 字幕生成套件',
      version: '官方文档 - 5.0 版本',
      c1: { title: '01. 概述', desc: '利用 Gemini 3 实现极速语音转录和精准对齐。' },
      c2: { title: '02. 时间轴编辑器', subtitle: '高级编辑工具', desc: '使用选择工具 (V) 移动，切割工具 (C) 切分片段，修剪工具 (Shift) 进行双向同步修剪。支持撤销 (Ctrl+Z)。' },
      c3: { title: '03. 样式与主题', uploadTitle: '调色盘', uploadDesc: '自定义字体和颜色。使用调色盘图标更改应用主题。', recTitle: '双语模式', recDesc: '原文与译文同步显示。' },
      c4: { title: '04. 搜索与替换', subtitle: '批量编辑', desc: '跨段落快速查找和修改。' },
      c5: { title: '05. 导出', subtitle: '专业格式', desc: '支持 SRT、ASS 或视频嵌入。' },
      c6: { title: '06. 导航', srtTitle: '时间码跳转', srtDesc: '点击时间轴上的时间码可立即跳转。', csvTitle: '快捷键', csvDesc: 'C: 切割, V: 选择, Shift: 同步修剪, Ctrl+Z: 撤销。' },
      c7: { title: '07. 隐私保护', desc: '数据安全处理，不永久存储音频。' }
    }
  },
  kr: {
    ...BASE_EN,
    appTitle: 'SubGenius',
    tagline: 'AI 기반 자막 생성기',
    config: '설정',
    targetLang: '대상 언어',
    generateBtn: '생성하기',
    processing: '처리 중...',
    cancel: '취소',
    uploadTitle: '오디오 업로드',
    exportSRT: 'SRT로 내보내기',
    saveProject: '저장',
    projects: '히스토리',
    search: '검색',
    recording: '녹음 중...',
    original: '원본',
    translation: '번역',
    newProject: '새 프로젝트',
    subtitleStyle: '자막 스타일',
    fontSize: '크기',
    fontColor: '색상',
    bgColor: '배경',
    bgOpacity: '불투명도',
    textAlign: '정렬',
    maxWidth: '최대 너비',
    exportVideo: '비디오 내보내기',
    exportSubtitles: '자막 내보내기',
    exportProject: '프로젝트 내보내기',
    videoFormat: '비디오 형식',
    renderingVideo: '비디오 렌더링 중...',
    ok: '확인',
    close: '닫기',
    start: '시작',
    end: '종료',
    noMedia: '미디어 연결 안 됨',
    selectMedia: '미디어 파일 선택',
    selectMediaHelp: '타임라인 미리보기 및 편집을 시작하려면 미디어 파일을 선택하십시오',
    guideTitle: '사용자 가이드',
    showSecondary: '원본 표시 (이중 자막)',
    originalReference: '원본 참조:',
    undo: '실행 취소',
    splitTool: '분할 도구',
    trimTool: '트림 도구',
    selectTool: '선택 도구',
    timecodeJump: '타임코드로 이동',
    themeSelect: '테마 선택',
    guide: {
      title: 'SubGenius AI - 사용자 가이드',
      tagline: '전문가용 AI 자막 생성 시스템',
      version: '공식 문서 - V5.0',
      c1: { title: '01. 개요', desc: 'Gemini 3를 활용한 초고속 오디오 전사 및 정밀 정렬.' },
      c2: { title: '02. 타임라인 편집기', subtitle: '고급 편집 도구', desc: '선택 도구(V)로 이동, 분할 도구(C)로 컷 편집, 트림 도구(Shift)로 양방향 동시 트림이 가능합니다. 실행 취소(Ctrl+Z)를 지원합니다.' },
      c3: { title: '03. 스타일 및 테마', uploadTitle: '스타일 팔레트', uploadDesc: '글꼴 및 색상 사용자 정의. 팔레트 아이콘으로 앱 테마를 변경하세요.', recTitle: '이중 자막', recDesc: '원본과 번역 동시 표시.' },
      c4: { title: '04. 검색 및 교체', subtitle: '일괄 편집', desc: '모든 세그먼트에서 용어 즉시 검색.' },
      c5: { title: '05. 내보내기', subtitle: '프로 포맷', desc: 'SRT, ASS 또는 비디오 오버레이.' },
      c6: { title: '06. 탐색', srtTitle: '타임코드 이동', srtDesc: '타임코드를 클릭하여 즉시 이동합니다.', csvTitle: '단축키', csvDesc: 'C: 분할, V: 선택, Shift: 동시 트림, Ctrl+Z: 실행 취소.' },
      c7: { title: '07. 개인정보', desc: '보안 처리. 서버에 오디오 영구 저장 안 함.' }
    }
  }
};
